# Generated by Django 4.0.3 on 2022-05-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('field_id', models.AutoField(primary_key=True, serialize=False)),
                ('field_title', models.CharField(max_length=50)),
                ('field_type', models.CharField(choices=[('SR', 'String'), ('IN', 'Integer'), ('FL', 'Float')], max_length=2)),
                ('field_hint', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductExtraFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_value', models.CharField(max_length=50)),
                ('field_id', models.ManyToManyField(to='Cats.fields')),
                ('product_id', models.ManyToManyField(to='Products.products')),
            ],
        ),
        migrations.CreateModel(
            name='Cats',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=100)),
                ('parent_id', models.IntegerField(null=True)),
                ('cat_icon', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('cat_fields', models.ManyToManyField(to='Cats.fields')),
            ],
        ),
    ]
